# Generated by Django 4.0.6 on 2022-07-22 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_weapon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('result', models.CharField(choices=[('W', 'Win'), ('L', 'Loss'), ('T', 'Tie')], default='W', max_length=1)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.character')),
            ],
        ),
    ]
