# Generated by Django 4.0.6 on 2022-07-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_battles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='battles',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='character',
            name='weapons',
            field=models.ManyToManyField(to='main_app.weapon'),
        ),
        migrations.AlterField(
            model_name='battles',
            name='date',
            field=models.DateField(verbose_name='Battle Date'),
        ),
    ]
